### ISSUE TITLE
Highlighting on slide decks

### ISSUE THREAD

**Issue by Im0** [network-automation/linklight#107]
On some slides, such as, [here](https://network-automation.github.io/linklight/decks/ansible-essentials.html#/37) there is meant to be a highlighted section (`name: install and start apache`).

It appears that the highlight.js code has been disabled:

`//{ src: 'https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.4.1/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } }`

When enabling it breaks the code blocks.  Suspecting there is a conflict between the highlighting and the yaml syntax scripts.

**Comment by IPvSean** [comment]
@liquidat is this something you could look at?  This is something broken with lightbulb vs linklight.  I am transitioning the f5 and networking decks to google slides / pdf because we have too many SVGs to manage.  For now I have no say in the master deck for server linux workshops... that is something not maintained by me..... what should we do here?

**Comment by liquidat** [comment]
@Im0 Works for me?
![Current screenshot](https://gist.githubusercontent.com/liquidat/129720e866b384977e5a6b5115b49b3a/raw/b24166c061a8ce168018d5b04d56515bf4cf9ac6/2018-10-07-linkligth-deck.png)
Maybe I'm missing something, what is wrong with the screenshot above?

@IPvSean Putting the decks to google slides or PDF makes it hard for anyone else to participate in them. I know that we have far too many SVGs flying around. But that is the only way I know of currently to keep them really modifiable.

**Comment by Im0** [comment]
@liquidat - On that slide, `- name: install and start apache` is enclosed in a mark statement.  This should highlight that line, so, people can see what you're talking about.  Go to the next slide, it mentions the hosts selector... this is enclosed in marks on that page, so, `hosts: web` should be highlights.

The highlight.js dependency has been disabled at the end of the file.  Obviously someone has had this problem in the past and disabled highlighting.  I've just raised this issue as a reminder.

**Comment by liquidat** [comment]
@Im0 Thanks for the details. I'll try to look into this but we are also thinking about if there are simpler ways to manage our presentations (other format, etc.), maybe we can fix this in the process.

**Comment by IPvSean** [comment]
this project is now the master for RHPDS for both RHEL workshop, network automation and f5 automation if that makes a difference?

**Comment by liquidat** [comment]
So, after a lot of discussion and way too much time we are going to change how we provide slide decks: they will be based upon Google Slides, and the old decks will move away. See [decks Readme in devel branch](https://github.com/network-automation/linklight/tree/devel/decks). This is not perfect, but what works for us right now.

For that reason I will close this bug (WONTFIX).
