### ISSUE TITLE
F5 Provisioner

### ISSUE THREAD

**Issue by jmcleroy** [network-automation/linklight#108]
When provisioning F5 workshop it occasionally throws the follow error. 

 ```FAILED! => {"changed": false, "msg": "tmsh -v\r\nSyntax Error: unexpected argument \"tmsh\"\r\nadmin@(ip-172-16-150-172)(cfg-sync Standalone)(Active)(/Common)(tmos)# "}```

Adding this for awareness.

**Comment by IPvSean** [comment]
has this ever happened again @jmcleroy ?  Any more details?  Shitty hotel wifi?  Airplane wifi?

**Comment by jmcleroy** [comment]
When it happens I can normally rerun and it will work you can close this as I think it is more environmental with AWS than with the playbook.
