### ISSUE TITLE
The ipaddr filter requires python-netaddr be installed on the ansible controller

### ISSUE THREAD

**Issue by rcalvaga** [network-automation/linklight#115]
Hello guys

I'm having next error using **special: all_cisco** and **networking: true**, but just on rtr3 & rtr4: 

**"The ipaddr filter requires python-netaddr be installed on the ansible controller"**

but python-netaddr is already installed on ansible controller:

**[root@ansible ~]# yum install python-netaddr**
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
**Package python-netaddr-0.7.5-9.el7.noarch already installed and latest version**
Nothing to do

Task is: **TASK [configure_routers : Apply router template]**

Could you help me? I'm trying to use Networking workshop V2.

Thanks a lot for your support!

**Comment by IPvSean** [comment]
hey @rcalvaga are you still having problems with this?

are you using ansible cli or tower?

**Comment by IPvSean** [comment]
@rcalvaga reopen this if you are still having problems

**Comment by bartmcleod** [comment]
I am experiencing this with Ansible 2.8.6. Pip3 claims to have installed ansible 2.9.2, but ansible --version says 2.8.6... But even before this, I got the error "The ipaddr filter requires python-netaddr be installed on the ansible controller"

**Comment by IPvSean** [comment]
@bartmcleod I would use a venv, check out the documentation here: https://docs.ansible.com/ansible/2.4/python_3_support.html . I have not had any luck NOT using venv and trying to have python2 and python3 side-by-side.  Talking to multiple developers and folks much smarter then me, I would ALWAYS use venvs this way and it will work much easier :)

**Comment by bartmcleod** [comment]
@IPvSean I ended up removing pip entirely, as it seemed pip3 was using Python 2.7 and I used pip to install ansible. So I removed every pip, then reinstalled pip3, removed ansible and reinstalled it using pip3. Then I could finally use pip to install netaddr and it finally recognized that it was not installed and everything worked fine after pip installed it for Python3. Sigh.

**Comment by MAdeelMalik** [comment]
Dear All 
I am receiving the same error and I did everything and no success

[root@12-sv-np ~]#  ansible-playbook /etc/ansible/core.yml --tags svi

PLAY [core switch configuration] ******************************************************************************************

TASK [SVI Configuration] **************************************************************************************************
fatal: [10.67.78.141]: FAILED! => {"changed": false, "msg": "**_The ipaddr filter requires python's netaddr be installed on the ansible controller_**"}

PLAY RECAP ****************************************************************************************************************
10.67.78.141               : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


Ansible version is this

**[root@12-sv-np ~]# ansible --version**
**ansible 2.9.5**
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/my_modules']
  **ansible python module location = /usr/lib/python3.6/site-packages/ansible**
  executable location = /bin/ansible
  **python version = 3.6.8** (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]

**Comment by joshland** [comment]
> **ansible 2.9.5**
> config file = /etc/ansible/ansible.cfg

This indicates you're using the system ansible.  I had a similar issue, and I did a 'hash -r' to clear my lookup hash.  

System:

```
(Python)  ✘ joshua@spetsnaz  ~/_git/x4900-core   master ●  ansible --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/joshua/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.6 (default, Jan 30 2020, 09:44:41) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]

```

Virtual Env:

```
(Python)  joshua@spetsnaz  ~/_git/x4900-core   master ●  hash -r         
(Python)  joshua@spetsnaz  ~/_git/x4900-core   master ●  ansible --version
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/joshua/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/joshua/_git/x4900-core/Python/lib64/python3.7/site-packages/ansible
  executable location = /home/joshua/_git/x4900-core/Python/bin/ansible
  python version = 3.7.6 (default, Jan 30 2020, 09:44:41) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
(Python)  joshua@spetsnaz  ~/_git/x4900-core   master ●  ansible-playbook sites.yml -i core0 

```

**Comment by jeevadotnet** [comment]
This worked for me:
`apt install --no-install-recommends python-netaddr`

**Comment by hoang-tranviet** [comment]
@jeevadotnet your command works for me!
Would you mind to explain the rationale behind this. Thanks!

**Comment by Doriangaensslen** [comment]
for Virtual Env you can use 
`pip3 install netaddr`

**Comment by kabab** [comment]
for python3 `sudo apt install --no-install-recommends python3-netaddr`

**Comment by sandisamp** [comment]
In my case it was simple case of exporting the PYTHONPATH variable before running the Ansible command

```
# pip3 install netaddr
Requirement already satisfied: netaddr in /usr/lib/python3.6/site-packages (0.7.19)

# export PYTHONPATH=/usr/lib/python3.6/site-packages/
```

**Comment by brian-lamb-software-engineer** [comment]
what i noticed, is when i ran `ansible --version`  it was using python 3.9.  
then i typed which pip3, it said /usr/bin/pip3.  then i went to /usr/bin and it `ls -la | grep pip` to uncover the exact name for pip39, and it was pip3.9.  So then i did `pip3.9 install netaddr`.  So essentially you have to use the same pip version as ansible is using for python.
