### ISSUE TITLE
Suggest reorganizing workshop page materials

### ISSUE THREAD

**Issue by kyleabenson** [network-automation/linklight#123]
We currently have 4 H2s on the landing page:
**Network Automation Workshops
Server Automation Workshops
Network Training Decks
Server Training Decks
Workshop Resources**

Last week during 3 workshops, one person each day ended up in the wrong workshop because they clicked on the first link (didn't listen to instructions)

I'll propose that since this page is dynamically created, we can use jinja2 to determine which resources should be created based on the type of workshop being provisioned. Would propose the following:

```
h1: Red Hat Ansible Automation {{ value }} Workshops

if route/switch:
h2: Network Automation Workshop Materials
route/switch V2 materials only

if F5:
h2: Network Automation Workshop Materials
f5 materials only

else:
h2: Linux Automation Workshop Materials
server essentials materials

h2: Workshop Resources
```

Does that sound good? Should drastically simplify this page and help reduce confusion.
Any objections?

@IPvSean @termlen0 @gdykeman

**Comment by IPvSean** [comment]
fixed with https://github.com/network-automation/linklight/pull/125
