### ISSUE TITLE
Issues with exercises not matching labs

### ISSUE THREAD

**Issue by kyleabenson** [network-automation/linklight#124]
We had some issues in 4 cities where people were confused with the number schemes of Labs slide VS lab exercises.

Ex: 
Many people would read 'time for lab 3.1' on the slide and find exercise 3.1, rather than 3.0.

We could break this into sections and then just have slides to introduce the sections, with the exercises matching what's on the slides for lab times.

@IPvSean @gdykeman @termlen0 ?

**Comment by IPvSean** [comment]
yeah we need to fix this

**Comment by IPvSean** [comment]
this will be fixed with https://github.com/network-automation/linklight/pull/130
