### ISSUE TITLE
"Previous Exercise" broken link

### ISSUE THREAD

**Issue by amayagil** [network-automation/linklight#1371]
### Area

Ansible Network Automation Workshop

### Proposed Changes

At the end of "Exercise 9: Creating a Workflow" (https://aap2.demoredhat.com/exercises/ansible_network/9-controller-workflow/) "Previous Exercise" link (https://aap2.demoredhat.com/exercises/ansible_network/8--controller-rbac/README.md) is broken

**Comment by IPvSean** [comment]
fixed and live on https://aap2.demoredhat.com/exercises/ansible_network/9-controller-workflow/
