### ISSUE TITLE
Broken Link in Windows Workshop - Ad hoc commands

### ISSUE THREAD

**Issue by cbolz** [network-automation/linklight#1379]
### Area

Ansible Windows Automation Workshop

### Proposed Changes

the ToC on https://aap2.demoredhat.com/exercises/ansible_windows/ has "Exercise 2 - Ad-hoc commands" - which is a broken link

**Comment by IPvSean** [comment]
![image](https://user-images.githubusercontent.com/6537680/137743271-168834b9-7009-440f-a371-f05900cfc043.png)
