### ISSUE TITLE
Provisioner fails with towerinstall: false

### ISSUE THREAD

**Issue by jimbarlow** [network-automation/linklight#149]
towerinstall: false when passed to the installer, for examplein the extra_vars.yml will cause failure
TASK [aws_dns : TURN OFF TOWER] *********************************************************************************************
fatal: [newtest-student1-ansible]: FAILED! => changed=true 
  cmd: ansible-tower-service stop
  delta: '0:00:00.003069'
  end: '2018-12-14 03:48:05.551301'
  msg: non-zero return code
  rc: 127
  start: '2018-12-14 03:48:05.548232'
  stderr: '/bin/sh: ansible-tower-service: command not found'
  stderr_lines:
  - '/bin/sh: ansible-tower-service: command not found'
  stdout: ''
  stdout_lines: <omitted>

It appears that logic to bypass the CERTS and DNS in Tower when not installed is required, perhaps with a "when: towerinstall"  conditional

**Comment by IPvSean** [comment]
@jimbarlow @jmcleroy can you confirm fix on latest master?

**Comment by jimbarlow** [comment]
I can confirm the fix works and allows a non-tower equipped workshop.   The Workshop Information template still generates a link for the tower instance when a non-towered workshop is provisioned.   Feel free to assign that patch to me.

**Comment by IPvSean** [comment]
from jim:
>I can confirm the fix works and allows a non-tower equipped workshop. The Workshop Information template still generates a link for the tower instance when a non-towered workshop is provisioned. Feel free to assign that patch to me.

@jimbarlow added another fix for the website, can you try again

**Comment by jimbarlow** [comment]
That fixed it!
