### ISSUE TITLE
Refernences to non-redhat sources

### ISSUE THREAD

**Issue by jwildman** [network-automation/linklight#158]
As an SA, I don't want to tell people about Ubuntu or how to download Ansible via pip.  Neither of those "enterprise" solutions, which is what I'm paid to sell.

**Comment by abenokraitis** [comment]
Ubuntu is still considered supported as a control node for Ansible Engine:
https://access.redhat.com/articles/3168091

Also, Ansible Tower is not available for download on the Customer Portal, and is supported on RHEL and CentOS:
https://docs.ansible.com/ansible-tower/latest/html/quickinstall/download_tower.html

Please provide specific examples in linklight you'd like changed, or submit PRs for proposing modifications.
