### ISSUE TITLE
Letsencrpyt Limit issue

### ISSUE THREAD

**Issue by jmcleroy** [network-automation/linklight#159]
##### SUMMARY

Appears to be a limit to how many certs you can create with letsencrypt. 

too many certificates already issued for: rhdemo.io: see https://letsencrypt.org/docs/rate-limits/\nPlease

##### ISSUE TYPE

 - Bug Report

##### EXTRA VARS FILE

```paste below

```

e.g. here is an example of an extra vars file we are looking for:
```
$ cat ~/Github/linklight/provisioner/seans_workshop.yml
---
ec2_region: us-east-1
ec2_name_prefix: seantest
student_total: 25
admin_password: ansible
create_login_page: true
```
for more information on the extra vars file please refer to: https://github.com/network-automation/linklight/blob/master/provisioner/README.md

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### PLAYBOOK SHORT OUTPUT

```paste below

```

##### PLAYBOOK LONG OUTPUT

```paste below

```

**Comment by IPvSean** [comment]
I have reached out to lets encrypt to make sure our limit as been increased.  Thanks to @sborenst for the tip

>Our weekly limit of certificates issued for your domain: rhdemo.io  has been increased to 4,000.  We raised it more than requested so that you have some overhead should you need a higher rate limit in the future.

>If you have a large integration, please read https://letsencrypt.org/docs/integration-guide/

>If you are wondering how many certificates you have used for a domain, you can use https://crt.sh/

>If you have any further questions about our rate limits, check out the doc https://letsencrypt.org/docs/rate-limits/ or post on our helpful Community Forums https://community.letsencrypt.org/

>Thanks for your support and for using Let's Encrypt!

>-Jenessa Petersen
Fundraising Specialist
