### ISSUE TITLE
teardown not working when instances are stopped

### ISSUE THREAD

**Issue by fridim** [network-automation/linklight#169]
##### SUMMARY

In our usecase, we automatically stop the instances after a while.
When teardown starts, the instances are not destroyed because of the filter used in ec2_instance_facts that select only **running** instances.
The playbook fails later when trying to delete security groups because they are used by instances.

Here is the fix we applied in our branch: https://github.com/redhat-gpte-devopsautomation/linklight/commit/d25c2f81536ca36f7c9d78afe95cabbc9171977c

**Comment by IPvSean** [comment]
will look at this

**Comment by IPvSean** [comment]
fixed in my branch, will merge soon
