### ISSUE TITLE
role to configure tower upon provision

### ISSUE THREAD

**Issue by IPvSean** [network-automation/linklight#192]
##### SUMMARY
we will add a role to the provisioner under `/provisioner` to allow tower to be per-configured with the 
- project
- inventory
- credentials

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
provisioner

##### ADDITIONAL INFORMATION
new role

**Comment by gdykeman** [comment]
![Alt Text](https://media1.tenor.com/images/c6609bccc44eb321f34c583496faccd3/tenor.gif?itemid=4384335)

**Comment by IPvSean** [comment]
https://github.com/network-automation/linklight/pull/211
