### ISSUE TITLE
Missing inventory set up

### ISSUE THREAD

**Issue by ronaldpetty** [network-automation/linklight#23]
The current published exercise:

https://network-automation.github.io/linklight/exercises/networking/1.1-adhoc/

Is missing the initial inventory setup.

https://github.com/network-automation/linklight/tree/master/exercises/ansible_engine/1-adhoc#step-11---define-your-inventory

**Comment by IPvSean** [comment]
For the networking workshop this is autogenerated for you and located in lab_inventory/hosts

e.g.->
`[student1@ip-172-16-2-165 ~]$ cat ~/networking-workshop/lab_inventory/hosts`

**can you let me know if this was not auto-generated?**  We might need to fix the instructions here and make the students aware of this right from the get go.... right now the 2nd exercise goes into this...
https://network-automation.github.io/linklight/exercises/networking/1.2-backup/

would appreciate thoughts / concerns... I think originally we were trying to avoid teaching lab_inventory until the student had run some quick ad-hoc commands...

**Comment by IPvSean** [comment]
@ronaldpetty is this still an issue?

**Comment by IPvSean** [comment]
closing because of lack of response
