### ISSUE TITLE
linklight/provisioner/hosts ansible_python_interpreter breaks lightbulb

### ISSUE THREAD

**Issue by rhcreynold** [network-automation/linklight#33]
Addition of ansible_python_interpreter in the hosts file break the lightbulb side.  commenting out it works fine. need to add logic

commit: f5771fd93ca08b88dbe167e4626e6802363eab85 #

**Comment by IPvSean** [comment]
@termlen0  did you get this fixed?

**Comment by termlen0** [comment]
Thanks @IPvSean  for fixing this.
