### ISSUE TITLE
Playbook path in Tower lab

### ISSUE THREAD

**Issue by willtome** [network-automation/linklight#35]
In this lab https://network-automation.github.io/linklight/exercises/networking/2.3-towerjob/ the path to the playbook to select is not available.

**Comment by ames7** [comment]
- change name of playbook to deploy_config.yml

**Comment by IPvSean** [comment]
This is fixed with https://github.com/network-automation/linklight/commit/f42b6f4b0798330637642fd55439432c8768ce9d

can you double check?

**Comment by IPvSean** [comment]
assuming this is fixed
