### ISSUE TITLE
Clarifying "Best Practices" for host files and/or .ansible.cfg

### ISSUE THREAD

**Issue by beeankha** [network-automation/linklight#38]
In the Ansible + Networking exercise 1.2 (https://github.com/network-automation/linklight/tree/master/exercises/networking/1.2-backup) step 4, even though the above sections talk about how the playbook is finding the host file due to the configuration of .ansible.cfg, it might be a good idea to mention *again* "Hey, a lot of times playbooks get executed in the same directory where hosts file lives but because we specified the .ansible.cfg file above, this playbook will find the hosts anywhere" or something like that.

**Comment by IPvSean** [comment]
What do you guys think @termlen0 and @gdykeman ?  I think we always use ~/.ansible.cfg but we don't talk about "best practices" per say here.... maybe we need a blurb somewhere?

**Comment by IPvSean** [comment]
bump @gdykeman ?

The more I think about it we need to move the ssh key declaration into the group vars in the inventory?

**Comment by termlen0** [comment]
IMO, as majority of attendees are new to Ansible, it is better to be more explicit with how inventories are being invoked.

**Comment by IPvSean** [comment]
by that do you mean using the -i parameter?  I think it would be better to explain the ansible.cfg file in more detail, otherwise our directions will look awful and there will be more typing for students.
