### ISSUE TITLE
update example in slides to work if copy/pasted

### ISSUE THREAD

**Issue by acozine** [network-automation/linklight#42]
On this slide:
https://network-automation.github.io/linklight/decks/ansible-networking.html#/37

The command shown:
`ansible -m ios_facts routers`
when done on a linklight control node, fails because `network_cli` is not set as the connection type.

Update the example to:
`ansible -m ios_facts routers -c network_cli`

**Comment by IPvSean** [comment]
fixed with https://github.com/network-automation/linklight/commit/4af9dcf536110b1d0d7e2090b81d4a9abd2f3247
