### ISSUE TITLE
Incorrect Directory Listed

### ISSUE THREAD

**Issue by beeankha** [network-automation/linklight#43]
In the Networking Training exercise 1.6, Roles (https://github.com/network-automation/linklight/tree/master/exercises/networking/1.5-roles), under section 7, the text:
`For roles/interfaces/tasks/static_route:`

...should read:
`For roles/static_route/tasks/main.yml:`

**Comment by IPvSean** [comment]
@beeankha can you check to make sure that makes sense now?

**Comment by beeankha** [comment]
Looks good!  Thank you!
