### ISSUE TITLE
Confusing directory structure for lab users

### ISSUE THREAD

**Issue by ames7** [network-automation/linklight#45]
Exercise 1.6 
	- very confusing on the wording of where you are supposed to be after everything else being done in the “networking_workshop” folder, confused people with the “test” folder structure. Perhaps reword or make it more clear the change in the directory.

**Comment by IPvSean** [comment]
I think I also fixed this with PR https://github.com/network-automation/linklight/commit/370e3ce72796b9a5fefaab10a42ec19e4f513cd5

can you check and make sure this is good?
