### ISSUE TITLE
no router_configs.yml in networking_workshop folder

### ISSUE THREAD

**Issue by ames7** [network-automation/linklight#46]
Exercise 1.6
Step 1
	- if following the “test” folder structure there is no router_configs.yml since its in the "networking-workshop” folder. Need to add a step to change into the networking_workshop folder or add the router_configs.yml earlier in the workshop.

**Comment by IPvSean** [comment]
can you review the latest push and see if that makes sense?  I personally think we need a lot more fixes and appreciate the input

**Comment by ames7** [comment]
Yeah that it explains it much better. Thanks!
