### ISSUE TITLE
ordering of things (ie, make the networking class options foremost)

### ISSUE THREAD

**Issue by medberry** [network-automation/linklight#47]
I noticed during a recent class I attended that there are some issues in the way various labs are presented to users. As this is the network-automation/linklight lab, I'd like to see the FIRST set of options presented be the Network lab options. This occurs in at least two places:

 during today's session to change the order.

I got to the WRONG labs by starting at this page:

https://network-automation.github.io/linklight/
It shows Ansible Engine Workshop foremost (but this particular repo is not specifically about Engine).

and as Sean C. noticed, the same issue happens on the generated TESTWORKSHOP.rhdemo.io page via the rectangle buttons where Ansible Networking appears as the third button (when read left to right like most of the world does). I'd just move networking to the forefront since by default, this deck is for networking workshops.

**Comment by IPvSean** [comment]
solved with your pr https://github.com/network-automation/linklight/pull/50
