### ISSUE TITLE
curl -O not working

### ISSUE THREAD

**Issue by medberry** [network-automation/linklight#51]
In the Lab exercise 2.1, step 3, Download the Latest Ansible Tower has us use "curl -O". However, that is not working on the newly built VM (though it is "succeeding" it isn't actually downloading anything.) wget is also available on the system at this time, so I suggest changing that command to wget.

Look for a PR shortly.

**Comment by gdykeman** [comment]
Could you try this link instead?

https://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-latest.tar.gz

Perhaps it's the http vs https...

**Comment by medberry** [comment]
The other (maybe better) solution is to add "-L" so it reads like this:

curl -L -O http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-latest.tar.gz
(and then it follows the http to https redirect properly.)

Again, I"m fine with any of the three.  wget does the redirect naturally.

**Comment by IPvSean** [comment]
while I perfer wget, and the provisioner does install this,  it is not installed by default on all operating systems so I am going err on caution and fix the bad link.  Check out PR https://github.com/network-automation/linklight/commit/c7aa90f9ecc663c41338e3edd45ff9a511dbc5dc
