### ISSUE TITLE
Add domain to sample-vars*

### ISSUE THREAD

**Issue by medberry** [network-automation/linklight#53]
I'd recommend adding the domain to the sample-vars* like this:

# switch domains by editing the following
# make sure domain has been create in Route 53 prior to running
#workshop_dns_zone: "rhdemo.io"

I didn't have an account that could update rhdemo.io so I created my one Route 53 and then the step that creates the LABNAME.worshop_dns_zone would succeed.

I'll work on a PR that does the above. (This is really just a "crutch" to help people setting up a linklight lab the very first time. But it is intended to be more OVERT and help people see how to do things.)

**Comment by IPvSean** [comment]
looking forward to PR

**Comment by as0bu** [comment]
@IPvSean I believe #99 may have satisfied this issue. So you might be able to close this out.

**Comment by IPvSean** [comment]
fixed with https://github.com/network-automation/linklight/pull/99, thanks @as0bu !
