### ISSUE TITLE
boto3 doesn't support properly environment variables

### ISSUE THREAD

**Issue by medberry** [network-automation/linklight#54]
Make a note in the docs/faq.md that boto3 has an issue with URIs manufactured from environment variables and to reiterate the best practices of using ~/.aws/credentials.

ref: http://bit.ly/2tKfaOP

**Comment by IPvSean** [comment]
@medberry can you do a echo $AWS_SECRET_ACCESS_KEY and $AWS_ACCESS_KEY_ID and compare that to your actual keys?  I imagine that quotes were incorrectly used and the env variable was not saved correctly.  Did a `\` disappear from the actual key and the variable?

e.g.
```
[test@test ~]$ export AWS_SECRET_ACCESS_KEY=blahblah\blahblahblah
[test@test ~]$ echo $AWS_SECRET_ACCESS_KEY
```
to see the env variable

**Comment by medberry** [comment]
Yes, I either had the env variable wrong (ie, AWS_ACCESS_KEY (wrong) instead of AWS_ACCESS_KEY_ID (right)) or misquoted... or possibly both. Sorry for the noise.

**Comment by medberry** [comment]
Sean, I'm not sure how to remove the "NEEDS LABEL" tag. (Maybe not necessary since closed but does show up in my github "dashboard" view of my issues.)

**Comment by IPvSean** [comment]
no worries I will close it!
