### ISSUE TITLE
Undefined variable "ansible_ios_version" is used

### ISSUE THREAD

**Issue by irixjp** [network-automation/linklight#70]
We need to use "ansible_net_version".

exercises/networking/1.5-roles/README.md
exercises/networking/1.5-roles/roles/static_route/tasks/main.yml
exercises/networking/1.5-roles/roles/interface/tasks/main.yml

**Comment by IPvSean** [comment]
fixed with https://github.com/network-automation/linklight/pull/74 to ansible_net_version
