### ISSUE TITLE
provision_lab.yml is requiring Ansible 2.6 but it seems that is not officially available

### ISSUE THREAD

**Issue by rcalvaga** [network-automation/linklight#8]
Hello guys. As you described within README, I'm using Ansible 2.5 for provisioning environments,  but recently I see that provision_lab.yml was updated:

    - name: make sure we are running correct Ansible Version
      assert:
        that:
          - ansible_version.minor >= 6
          - ansible_version.major >= 2

   - name: grab information about AWS user
     aws_caller_facts:
          region: "{{ ec2_region }}"
     register: whoami

It' seems that Ansible 2.6 is necessary for aws_caller_facts, but in my understanding it's in development stage right now, isn't it?
 
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

Because I'm having an error using Ansible 2.5. Could you help me with that?

Thanks in advance!

**Comment by IPvSean** [comment]
Hey Robert,

The 2.6 branch is still in devel but you grab a nightly rpm here:

https://releases.ansible.com/ansible/rpm/nightly/devel/epel-6-x86_64/

Install with a yum install local

Sorry about the requirement, otherwise AWS api is not consistent with the
2.5 modules and we will end up with unhappy users because random tasks will
report errors and timeouts

**Comment by IPvSean** [comment]
Hey Robert, does that work for you?

**Comment by rcalvaga** [comment]
Hey Sean! How you doing today?

I'm sorry for the delay. I'm just trying to install but it seems that Python 2.6 is required and I'm using Python 2.7:

Error: Package: ansible-2.6.0-0.0.devel.201805082046git.ea489b3f33.el6.ans.noarch (/ansible-2.6.0-0.0.devel.201805082046git.ea489b3f33.el6.ans.noarch)
           Requires: /usr/bin/python2.6

Thanks a lot for your quick response and support!

**Comment by IPvSean** [comment]
if you are not using tower... it might be easier for you to just use pip to install dev branch quickly->

```
pip install git+https://github.com/ansible/ansible.git@devel
```

more directions at-> http://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html

**Comment by rcalvaga** [comment]
Dear Sean,

After that, everything is working like a charm.

Thanks for your kind support!

Regards.
