### ISSUE TITLE
short_name breaks non networking installs

### ISSUE THREAD

**Issue by rhcreynold** [network-automation/linklight#88]
using latest 2.7 devel:

ASK [common : hostname] ********************************************************************************************************************************************************************************************************************
fatal: [rdu-student39-node1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'short_name' is undefined\n\nThe error appears to have been in '/root/creynold/linklight/provisioner/roles/common/tasks/main.yml': line 16, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- hostname:\n  ^ here\n"}                                                               
fatal: [rdu-student48-node1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'short_name' is undefined\n\nThe error appears to have been in '/root/creynold/linklight/provisioner/roles/common/tasks/main.yml': line 16, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- hostname:\n  ^ here\n"}                                                               
fatal: [rdu-student25-node1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'short_name' is undefined\n\nThe error appears to have been in '/root/creynold/linklight/provisioner/roles/common/tasks/main.yml': line 16, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- hostname:\n  ^ here\n"}                                                               
fatal: [rdu-student15-node1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'short_name' is undefined\n\nThe error appears to have been in '/root/creynold/linklight/provisioner/roles/common/tasks/main.yml': line 16, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- hostname:\n  ^ here\n"}                                                               
fatal: [rdu-student4-node1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'short_name' is undefined\n\nThe error appears to have been in '/root/creynold/linklight/provisioner/roles/common/tasks/main.yml': line 16, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- hostname:\n  ^ here\n"}                                                                
fatal: [rdu-student3-node1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'short_name' is undefined\n\nThe error appears to have been in '/root/creynold/linklight/provisioner/roles/common/tasks/main.yml': line 16, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- hostname:\n  ^ here\n"}                                                                
fatal: [rdu-student45-node1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'short_name' is undefined\n\nThe error appears to have been in '/root/creynold/linklight/provisioner/roles/common/tasks/main.yml': line 16, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- hostname:\n  ^ here\n"}                                                               
fatal: [rdu-student8-node1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'short_name' is undefined\n\nThe error appears to have been in '/root/creynold/linklight/provisioner/roles/common/tasks/main.yml': line 16, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- hostname:\n  ^ here\n"}

**Comment by LDSanches** [comment]
Modify the file roles/manage_ec2_instances/tasks/provision.yml, changing the lines 71, 72, 73 and 75. See:

- name: Ensure tags are present
  ec2_tag:
    region: "{{ ec2_region }}"
    resource: "{{item.1}}"
    state: present
    tags:
      Name: "{{ ec2_name_prefix }}-student{{item.0 + 1}}-ansible"
      Workshop_ansible: "{{ec2_name_prefix}}-ansible"
      Workshop: "{{ec2_name_prefix}}"
      Index: "{{ item[0] }}"
      Student: "student{{item.0 + 1}}"
      Username: "{{ linklight_user }}"
      Info: "Username that provisioned this-> {{ linklight_user }}"
      Linklight: "This was provisioned through the linklight provisioner"
      Students: "{{student_total}}"
#<<<<<<< HEAD
#      short_name: ansible
#=======
      short_name: "ansible"
#>>>>>>> master
  with_indexed_items:
    - "{{ control_output.instance_ids }}"
  when: control_output.instance_ids is not none

**Comment by IPvSean** [comment]
i think this is fixed, can you guys retry?

**Comment by LDSanches** [comment]
Done, this point is working fine! Thanks for your help.
