### ISSUE TITLE
Network v2 requires you to subscribe to the CSR1000V instance

### ISSUE THREAD

**Issue by steven-ellis** [network-automation/linklight#90]
This isn't clearly documented and throws an error during the first attempt at running the playbook

```
TASK [manage_ec2_instances : Create EC2 instances for rtr1 node (NETWORKING MODE)] ************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Instance creation failed => OptInRequired: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=5tiyrfb5tasxk9gmnab39b843"}
```

Current Marketplace URL

- https://aws.amazon.com/marketplace/pp/B00NF48FI2/

This should be noted in the documentation or in the FAQ

**Comment by IPvSean** [comment]
Hey @steven-ellis sucks you are so far away on time zones, hopefully this fixes the issue for you, thanks for opening!!  This kind of information is super helpful.  Fixed with https://github.com/network-automation/linklight/tree/master/provisioner

**Comment by IPvSean** [comment]
meant: https://github.com/network-automation/linklight/commit/10fa1b3e68516e61f87baa5846c9053fc043de0b
