### ISSUE TITLE
aws_workshop_login_page : DNS for student webpage

### ISSUE THREAD

**Issue by LDSanches** [network-automation/linklight#92]
Hello guys, 

Could you please help me with this issue?

My Domain "redhatbr.io" is working fine, but the error below was presented during the perform of provision_lab.yml playbook.

TASK [aws_workshop_login_page : DNS for student webpage] *************************************************************************************************************************************
task path: /home/lsanches/GIT-REDHAT/linklight/provisioner/roles/aws_workshop_login_page/tasks/main.yml:23
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: lsanches
<127.0.0.1> EXEC /bin/sh -c 'echo ~lsanches && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/lsanches/.ansible/tmp/ansible-tmp-1533752478.27-111969520333191 `" && echo ansible-tmp-1533752478.27-111969520333191="` echo /home/lsanches/.ansible/tmp/ansible-tmp-1533752478.27-111969520333191 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/amazon/route53.py
<127.0.0.1> PUT /home/lsanches/.ansible/tmp/ansible-local-28668FaGJiK/tmpKVTuCF TO /home/lsanches/.ansible/tmp/ansible-tmp-1533752478.27-111969520333191/route53.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/lsanches/.ansible/tmp/ansible-tmp-1533752478.27-111969520333191/ /home/lsanches/.ansible/tmp/ansible-tmp-1533752478.27-111969520333191/route53.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/lsanches/.ansible/tmp/ansible-tmp-1533752478.27-111969520333191/route53.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/lsanches/.ansible/tmp/ansible-tmp-1533752478.27-111969520333191/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "alias": null, 
            "alias_evaluate_target_health": false, 
            "alias_hosted_zone_id": null, 
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "ec2_url": null, 
            "failover": null, 
            "health_check": null, 
            "hosted_zone_id": null, 
            "identifier": null, 
            "overwrite": true, 
            "private_zone": false, 
            "profile": null, 
            "record": "testdrivebr.redhatbr.io", 
            "region": null, 
            "retry_interval": "500", 
            "security_token": null, 
            "state": "present", 
            "ttl": 3600, 
            "type": "CNAME", 
            "validate_certs": true, 
            "value": [
                "testdrivebr.redhatbr.io.s3-website-us-east-1.amazonaws.com"
            ], 
            "vpc_id": null, 
            "wait": false, 
            "wait_timeout": 300, 
            "weight": null, 
            "zone": "redhatbr.io"
        }
    }, 
    "msg": "Zone redhatbr.io. does not exist in Route53"
}

PLAY RECAP ***********************************************************************************************************************************************************************************
TestDriveBR-student1-ansible : ok=24   changed=4    unreachable=0    failed=0   
TestDriveBR-student1-host1 : ok=6    changed=0    unreachable=0    failed=0   
localhost                  : ok=62   changed=7    unreachable=0    failed=1

**Comment by IPvSean** [comment]
So the error leads me that redhatbr.io is not right->
```
"msg": "Zone redhatbr.io. does not exist in Route53"
```

login to the AWS web console then click services, click route53 then see if its there....  you sure your AWS id has access to that?  Do you have multiple accounts?

**Comment by LDSanches** [comment]
Done! All process was performed without issues.

Thanks
